import * as React from "react";
import Box from "@mui/material/Box";
import { useTheme } from "@mui/material/styles";
import MobileStepper from "@mui/material/MobileStepper";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";
import { Quiniela } from "./Quiniela";
import axios from "axios";

export function CarruselMUIText() {
  const theme = useTheme();
  const [activeStep, setActiveStep] = React.useState(0);
  const [match, setMatches] = React.useState([]);
  // data.slice(0, 32); //16avos de final
  // data.slice(0, 16); //8vos de final
  // data.slice(0, 8); //4tos de final
  // data.slice(0, 4); //Semis
  // data.slice(5, 8); //Tercer puesto
  // data.slice(0, 2); //Final

  const dataDePrueba = {
    octavos: [
      {
        matchId: "2270583212125",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1668959940,
        status: 0,
        homeId: "904",
        homeName: "Qatar",
        awayId: "779",
        awayName: "Ecuador",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        location: "Khalifa International",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "11235267058129",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669035600,
        halfStartTime: 0,
        status: 0,
        homeId: "744",
        homeName: "England",
        awayId: "783",
        awayName: "Iran",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "771221237058126",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669046340,
        status: 0,
        homeId: "815",
        homeName: "Senegal",
        awayId: "646",
        awayName: "Netherlands",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "341232193358121",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669057200,
        halfStartTime: 0,
        status: 0,
        homeId: "797",
        homeName: "USA",
        awayId: "7384",
        awayName: "Wales",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "22705812339875",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1668959940,
        status: 0,
        homeId: "904",
        homeName: "Qatar",
        awayId: "779",
        awayName: "Ecuador",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        location: "Khalifa International",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "267058108765429",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669035600,
        halfStartTime: 0,
        status: 0,
        homeId: "744",
        homeName: "England",
        awayId: "783",
        awayName: "Iran",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "23705678958126",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669046340,
        status: 0,
        homeId: "815",
        homeName: "Senegal",
        awayId: "646",
        awayName: "Netherlands",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "39541335812144",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669057200,
        halfStartTime: 0,
        status: 0,
        homeId: "797",
        homeName: "USA",
        awayId: "7384",
        awayName: "Wales",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
    ],
    cuartos: [
      {
        matchId: "2273312321058125",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1668959940,
        status: 0,
        homeId: "904",
        homeName: "Qatar",
        awayId: "779",
        awayName: "Ecuador",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        location: "Khalifa International",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "267058789863129",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669035600,
        halfStartTime: 0,
        status: 0,
        homeId: "744",
        homeName: "England",
        awayId: "783",
        awayName: "Iran",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "23703458125546",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669046340,
        status: 0,
        homeId: "815",
        homeName: "Senegal",
        awayId: "646",
        awayName: "Netherlands",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "3933586775433121",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669057200,
        halfStartTime: 0,
        status: 0,
        homeId: "797",
        homeName: "USA",
        awayId: "7384",
        awayName: "Wales",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
    ],
    semifinales: [
      {
        matchId: "22707600358125",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1668959940,
        status: 0,
        homeId: "904",
        homeName: "Qatar",
        awayId: "779",
        awayName: "Ecuador",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        location: "Khalifa International",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "267058122987429",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669035600,
        halfStartTime: 0,
        status: 0,
        homeId: "744",
        homeName: "England",
        awayId: "783",
        awayName: "Iran",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
    ],
    final: [
      {
        matchId: "227058155573225",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1668959940,
        status: 0,
        homeId: "904",
        homeName: "Qatar",
        awayId: "779",
        awayName: "Ecuador",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "A",
        location: "Khalifa International",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
      {
        matchId: "26705812955986332",
        leagueId: "1572",
        leagueName: "FIFA World Cup",
        leagueShortName: "World Cup",
        matchTime: 1669035600,
        halfStartTime: 0,
        status: 0,
        homeId: "744",
        homeName: "England",
        awayId: "783",
        awayName: "Iran",
        homeScore: 0,
        awayScore: 0,
        homeHalfScore: 0,
        awayHalfScore: 0,
        homeRed: 0,
        awayRed: 0,
        homeYellow: 0,
        awayYellow: 0,
        homeCorner: 0,
        awayCorner: 0,
        homeRank: "",
        awayRank: "",
        season: "2022",
        stageId: "21534",
        round: "Groups",
        group: "B",
        extraExplain: {
          kickOff: 0,
          minute: 0,
          homeScore: 0,
          awayScore: 0,
          extraTimeStatus: 0,
          extraHomeScore: 0,
          extraAwayScore: 0,
          penHomeScore: 0,
          penAwayScore: 0,
          twoRoundsHomeScore: 0,
          twoRoundsAwayScore: 0,
          winner: 0,
        },
      },
    ],
  };

  const steps = [
    {
      label: "Fase de Grupos",
      description: (
        <Quiniela phase="Grupos" arrayDePartidos={match?.slice(0, 48)} />
      ),
    },
    {
      label: "Octavos de final",
      description: (
        <Quiniela phase="Octavos" arrayDePartidos={dataDePrueba.octavos} />
      ),
    },
    {
      label: "Cuartos de final",
      description: (
        <Quiniela phase="Cuartos" arrayDePartidos={dataDePrueba.cuartos} />
      ),
    },
    {
      label: "Semifinales",
      description: (
        <Quiniela
          phase="Semifinales"
          arrayDePartidos={dataDePrueba.semifinales}
        />
      ),
    },
    {
      label: "Final",
      description: (
        <Quiniela phase="Final" arrayDePartidos={dataDePrueba.final} />
      ),
    },
  ];

  // const steps = [
  //   {
  //     label: "Fase de Grupos",
  //     description: <Quiniela arrayDePartidos={match?.slice(0, 48)} />,
  //   },
  //   {
  //     label: "Octavos de final",
  //     description: <Quiniela arrayDePartidos={match?.slice(39, -1)} />,
  //   },
  //   {
  //     label: "Cuartos de final",
  //     description: <Quiniela arrayDePartidos={match?.slice(43, -1)} />,
  //   },
  //   {
  //     label: "Semifinales",
  //     description: <Quiniela arrayDePartidos={match?.slice(45, -1)} />,
  //   },
  //   {
  //     label: "Final",
  //     description: <Quiniela arrayDePartidos={match?.slice(20, -26)} />,
  //   },
  // ];

  const maxSteps = steps.length;

  const getMatches = async () => {
    await axios
      .get(
        "http://api.isportsapi.com/sport/football/schedule?api_key=7ysUHBwXouU3Bb48&leagueId=1572"
      )
      .then((res) => setMatches(res.data.data));

    /////para hacer pruebas con champions league
    // axios
    //   .get(
    //     "http://api.isportsapi.com/sport/football/schedule?api_key=7ysUHBwXouU3Bb48&leagueId=13014"
    //   )
    //   .then((res) => {
    //     const resultado = res.data.data.filter((obj) => obj.group != "");
    //     return setMatches(resultado);
    //   });
    // console.log(match);

    // setMatches([
    //   {
    //     matchId: "227058125",
    //     leagueType: 2,
    //     leagueId: "1572",
    //     leagueName: "FIFA World Cup",
    //     leagueShortName: "World Cup",
    //     leagueColor: "#660000",
    //     subLeagueId: "",
    //     subLeagueName: "",
    //     matchTime: 1668959940,
    //     halfStartTime: 0,
    //     status: 0,
    //     homeId: "904",
    //     homeName: "Qatar",
    //     awayId: "779",
    //     awayName: "Ecuador",
    //     homeScore: 0,
    //     awayScore: 0,
    //     homeHalfScore: 0,
    //     awayHalfScore: 0,
    //     homeRed: 0,
    //     awayRed: 0,
    //     homeYellow: 0,
    //     awayYellow: 0,
    //     homeCorner: 0,
    //     awayCorner: 0,
    //     homeRank: "",
    //     awayRank: "",
    //     season: "2022",
    //     stageId: "21534",
    //     round: "Groups",
    //     group: "A",
    //     location: "Khalifa International",
    //     weather: "",
    //     temperature: "",
    //     explain: "",
    //     extraExplain: {
    //       kickOff: 0,
    //       minute: 0,
    //       homeScore: 0,
    //       awayScore: 0,
    //       extraTimeStatus: 0,
    //       extraHomeScore: 0,
    //       extraAwayScore: 0,
    //       penHomeScore: 0,
    //       penAwayScore: 0,
    //       twoRoundsHomeScore: 0,
    //       twoRoundsAwayScore: 0,
    //       winner: 0,
    //     },
    //     hasLineup: false,
    //     neutral: false,
    //   },
    //   {
    //     matchId: "267058129",
    //     leagueType: 2,
    //     leagueId: "1572",
    //     leagueName: "FIFA World Cup",
    //     leagueShortName: "World Cup",
    //     leagueColor: "#660000",
    //     subLeagueId: "",
    //     subLeagueName: "",
    //     matchTime: 1669035600,
    //     halfStartTime: 0,
    //     status: 0,
    //     homeId: "744",
    //     homeName: "England",
    //     awayId: "783",
    //     awayName: "Iran",
    //     homeScore: 0,
    //     awayScore: 0,
    //     homeHalfScore: 0,
    //     awayHalfScore: 0,
    //     homeRed: 0,
    //     awayRed: 0,
    //     homeYellow: 0,
    //     awayYellow: 0,
    //     homeCorner: 0,
    //     awayCorner: 0,
    //     homeRank: "",
    //     awayRank: "",
    //     season: "2022",
    //     stageId: "21534",
    //     round: "Groups",
    //     group: "B",
    //     location: "",
    //     weather: "",
    //     temperature: "",
    //     explain: "",
    //     extraExplain: {
    //       kickOff: 0,
    //       minute: 0,
    //       homeScore: 0,
    //       awayScore: 0,
    //       extraTimeStatus: 0,
    //       extraHomeScore: 0,
    //       extraAwayScore: 0,
    //       penHomeScore: 0,
    //       penAwayScore: 0,
    //       twoRoundsHomeScore: 0,
    //       twoRoundsAwayScore: 0,
    //       winner: 0,
    //     },
    //     hasLineup: false,
    //     neutral: true,
    //   },
    //   {
    //     matchId: "237058126",
    //     leagueType: 2,
    //     leagueId: "1572",
    //     leagueName: "FIFA World Cup",
    //     leagueShortName: "World Cup",
    //     leagueColor: "#660000",
    //     subLeagueId: "",
    //     subLeagueName: "",
    //     matchTime: 1669046340,
    //     halfStartTime: 0,
    //     status: 0,
    //     homeId: "815",
    //     homeName: "Senegal",
    //     awayId: "646",
    //     awayName: "Netherlands",
    //     homeScore: 0,
    //     awayScore: 0,
    //     homeHalfScore: 0,
    //     awayHalfScore: 0,
    //     homeRed: 0,
    //     awayRed: 0,
    //     homeYellow: 0,
    //     awayYellow: 0,
    //     homeCorner: 0,
    //     awayCorner: 0,
    //     homeRank: "",
    //     awayRank: "",
    //     season: "2022",
    //     stageId: "21534",
    //     round: "Groups",
    //     group: "A",
    //     location: "",
    //     weather: "",
    //     temperature: "",
    //     explain: "",
    //     extraExplain: {
    //       kickOff: 0,
    //       minute: 0,
    //       homeScore: 0,
    //       awayScore: 0,
    //       extraTimeStatus: 0,
    //       extraHomeScore: 0,
    //       extraAwayScore: 0,
    //       penHomeScore: 0,
    //       penAwayScore: 0,
    //       twoRoundsHomeScore: 0,
    //       twoRoundsAwayScore: 0,
    //       winner: 0,
    //     },
    //     hasLineup: false,
    //     neutral: true,
    //   },
    //   {
    //     matchId: "393358121",
    //     leagueType: 2,
    //     leagueId: "1572",
    //     leagueName: "FIFA World Cup",
    //     leagueShortName: "World Cup",
    //     leagueColor: "#660000",
    //     subLeagueId: "",
    //     subLeagueName: "",
    //     matchTime: 1669057200,
    //     halfStartTime: 0,
    //     status: 0,
    //     homeId: "797",
    //     homeName: "USA",
    //     awayId: "7384",
    //     awayName: "Wales",
    //     homeScore: 0,
    //     awayScore: 0,
    //     homeHalfScore: 0,
    //     awayHalfScore: 0,
    //     homeRed: 0,
    //     awayRed: 0,
    //     homeYellow: 0,
    //     awayYellow: 0,
    //     homeCorner: 0,
    //     awayCorner: 0,
    //     homeRank: "",
    //     awayRank: "",
    //     season: "2022",
    //     stageId: "21534",
    //     round: "Groups",
    //     group: "B",
    //     location: "",
    //     weather: "",
    //     temperature: "",
    //     explain: "",
    //     extraExplain: {
    //       kickOff: 0,
    //       minute: 0,
    //       homeScore: 0,
    //       awayScore: 0,
    //       extraTimeStatus: 0,
    //       extraHomeScore: 0,
    //       extraAwayScore: 0,
    //       penHomeScore: 0,
    //       penAwayScore: 0,
    //       twoRoundsHomeScore: 0,
    //       twoRoundsAwayScore: 0,
    //       winner: 0,
    //     },
    //     hasLineup: false,
    //     neutral: true,
    //   },
    // ]);
  };

  React.useEffect(() => {
    getMatches();
  }, []);

  const handleNext = () => {
    setActiveStep((prevActiveStep) => prevActiveStep + 1);
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1);
  };

  return (
    <Box sx={{ maxWidth: 400, flexGrow: 1 }}>
      <MobileStepper
        variant="text"
        steps={maxSteps}
        position="static"
        activeStep={activeStep}
        nextButton={
          <Button
            size="small"
            onClick={handleNext}
            disabled={activeStep === maxSteps - 1}
          >
            Next
            {theme.direction === "rtl" ? (
              <KeyboardArrowLeft />
            ) : (
              <KeyboardArrowRight />
            )}
          </Button>
        }
        backButton={
          <Button size="small" onClick={handleBack} disabled={activeStep === 0}>
            {theme.direction === "rtl" ? (
              <KeyboardArrowRight />
            ) : (
              <KeyboardArrowLeft />
            )}
            Back
          </Button>
        }
      />
      <Paper
        square
        elevation={0}
        sx={{
          display: "flex",
          alignItems: "center",
          height: 50,
          pl: 2,
          bgcolor: "background.default",
        }}
      >
        <Typography>{steps[activeStep].label}</Typography>
      </Paper>
      {/* <Box sx={{ height: 255, maxWidth: 400, width: "100%", p: 2 }}>
        {steps[activeStep].description}
      </Box> */}
      {steps[activeStep].description}
    </Box>
  );
}
