import { useCallback, useContext, useEffect, useState } from "react";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";
import { Button } from "@mui/material";
import { AuthContext } from "../context";
import { AxiosConfig } from "../utils";
import axios from "axios";
import Swal from "sweetalert2";

// export const QuinielaPlayer = ({ disabled }) => {
//   return (
//     <>
//       <Autocomplete
//         disablePortal
//         id="combo-box-demo"
//         options={top100Films}
//         sx={{ width: 300 }}
//         disabled={disabled}
//         renderInput={(params) => (
//           <TextField
//             required={true}
//             {...params}
//             label="Jugador"
//             InputProps={{ inputProps: { value: "Hola" } }}
//           />
//         )}
//       />
//       <TextField
//         id="outlined-number"
//         label="Goles"
//         type="number"
//         InputLabelProps={{
//           shrink: true,
//         }}
//         required={true}
//         disabled={disabled}
//         InputProps={{ inputProps: { min: 1, value: 5 } }}
//       />
//     </>
//   );
// };

export const QuinielaPlayer = ({ disabled }) => {
  const { userAuth } = useContext(AuthContext);
  const [player, setPlayer] = useState({});
  const [update, setUpdate] = useState("");

  const addPlayer = async () => {
    console.log(player);
    if (disabled) return console.log("No ha terminado la fase anterior");

    if (!!player?.name < 1 || !!player?.goals < 1)
      return Swal.fire({
        title: "Hay campos vacios!",
        text: "Toda la quiniela debe estar llena",
        icon: "info",
        confirmButtonText: "Ok",
      });

    const TOKEN = userAuth;

    const res = await AxiosConfig.get("auth/private", {
      headers: {
        Authorization: `Bearer ${TOKEN}`,
      },
    });
    const userId = res.data.user._id;

    const { data } = await AxiosConfig.get(`player/findOneByUserId/${userId}`);

    if (!!data) {
      // actualizar player
      const goals = Number(player.goals);
      const name = player.name;

      const body = {
        name,
        goals,
      };

      await axios.put(`http://localhost:3000/player/${data._id}`, body, {
        headers: { Authorization: `Bearer ${TOKEN}` },
      });

      Swal.fire({
        title: "Listo!",
        text: "Tu predicción se ha actualizado correctamente.",
        icon: "success",
        confirmButtonText: "Ok",
      });
    } else {
      const goals = Number(player.goals);
      const name = player.name;

      const body = {
        name,
        goals,
      };

      await axios.post("http://localhost:3000/player/create", body, {
        headers: { Authorization: `Bearer ${TOKEN}` },
      });

      Swal.fire({
        title: "Listo!",
        text: "Tu predicción se ha creado correctamente.",
        icon: "success",
        confirmButtonText: "Ok",
      });
    }
  };

  const returnDefaultValue = useCallback(() => {
    if (!!player?.name) {
      for (let index = 0; index < data.length; index++) {
        if (data[index].name === player?.name) {
          return index;
        } else {
          continue;
        }
      }
    } else {
      return false;
    }
  }, [player]);

  const onAddPlayer = (value, key) => {
    setPlayer((prevState) => ({
      ...prevState,
      [key]: value,
    }));
  };

  const getPlayer = useCallback(async () => {
    const TOKEN = userAuth;

    const response = await AxiosConfig.get("auth/private", {
      headers: {
        Authorization: `Bearer ${TOKEN}`,
      },
    });
    const userId = response.data.user._id;

    const { data } = await AxiosConfig.get(`player/findOneByUserId/${userId}`);
    if (!!data === false) return;
    delete data.userId;
    delete data.__v;
    delete data._id;

    setPlayer(data);
  }, [userAuth]);

  // const getPlayersFromApi = async ({ target }) => {
  // const results = await axios.get(
  //   `http://api.isportsapi.com/sport/football/player/search?api_key=EGlD1j0CeqDo3hcr&name=${target.value}`
  // );
  // console.log(results.data.data.map((res) => res.name));
  // const result = data.filter((jugador) =>
  //   jugador.label.includes(target.value)
  // );
  // console.log(result);
  // };

  useEffect(() => {
    getPlayer();
  }, [getPlayer]);

  useEffect(() => {
    setUpdate(data[returnDefaultValue()]);
  }, [returnDefaultValue, player]);

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
      }}
    >
      <Autocomplete
        disablePortal
        id="combo-box-demo"
        options={data}
        sx={{ width: 300 }}
        value={update || null}
        disabled={disabled}
        getOptionLabel={(option) => option.name}
        onInputChange={(e, value) => onAddPlayer(value, "name")}
        isOptionEqualToValue={(option, value) => option.name === value.name}
        renderInput={(params) => (
          <TextField
            type="text"
            name="name"
            required={true}
            {...params}
            label="Goleador del Mundial"
          />
        )}
      />
      <TextField
        id="outlined-number"
        label="Goles"
        name="goals"
        type="number"
        onChange={(e) => onAddPlayer(e.target.value, "goals")}
        required={true}
        disabled={disabled}
        InputProps={{ inputProps: { min: 1, value: player?.goals || "" } }}
      />

      {/* <input type="text" onChange={getPlayersFromApi} placeholder="Search.." /> */}

      <Button variant="contained" disabled={disabled} onClick={addPlayer}>
        Enviar
      </Button>
    </form>
  );
};

const data = [
  {
    playerId: "150860",
    name: "Erling Haaland",
    teamId: "26",
    teamName: "Manchester City",
    country: "Norway",
    goalsCount: 5,
    homeGoals: 3,
    awayGoals: 2,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "120561",
    name: "Leroy Sane",
    teamId: "88",
    teamName: "Bayern Munchen",
    country: "Germany",
    goalsCount: 4,
    homeGoals: 3,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "168137",
    name: "Giacomo Raspadori",
    teamId: "1419",
    teamName: "Napoli",
    country: "Italy",
    goalsCount: 3,
    homeGoals: 0,
    awayGoals: 3,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 1,
  },
  {
    playerId: "103092",
    name: "Piotr Zielinski",
    teamId: "1419",
    teamName: "Napoli",
    country: "Poland",
    goalsCount: 3,
    homeGoals: 2,
    awayGoals: 1,
    homePenalty: 1,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "171424",
    name: "Mohammed Kudus",
    teamId: "253",
    teamName: "AFC Ajax",
    country: "Ghana",
    goalsCount: 3,
    homeGoals: 2,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "178042",
    name: "Jude Bellingham",
    teamId: "99",
    teamName: "Borussia Dortmund",
    country: "England",
    goalsCount: 3,
    homeGoals: 1,
    awayGoals: 2,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "165972",
    name: "Noah Okafor",
    teamId: "9",
    teamName: "Red Bull Salzburg",
    country: "Switzerland",
    goalsCount: 3,
    homeGoals: 2,
    awayGoals: 1,
    homePenalty: 1,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "60961",
    name: "Robert Lewandowski",
    teamId: "84",
    teamName: "FC Barcelona",
    country: "Poland",
    goalsCount: 3,
    homeGoals: 3,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "144812",
    name: "Kylian Mbappe Lottin",
    teamId: "271",
    teamName: "Paris Saint Germain (PSG)",
    country: "France",
    goalsCount: 3,
    homeGoals: 2,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "196127",
    name: "Ferran Jutgla Blanch",
    teamId: "148",
    teamName: "Club Brugge",
    country: "Spain",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 1,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "198068",
    name: "Mykhailo Mudryk",
    teamId: "716",
    teamName: "FC Shakhtar Donetsk",
    country: "Ukraine",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "153244",
    name: "Vinicius Jose Paixao de Oliveira Junior",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Brazil",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "24067",
    name: "Lionel Andres Messi",
    teamId: "271",
    teamName: "Paris Saint Germain (PSG)",
    country: "Argentina",
    goalsCount: 2,
    homeGoals: 0,
    awayGoals: 2,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "115999",
    name: "Giovanni Pablo Simeone",
    teamId: "1419",
    teamName: "Napoli",
    country: "Argentina",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "164379",
    name: "Alexis Saelemaekers",
    teamId: "150",
    teamName: "AC Milan",
    country: "Belgium",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "101663",
    name: "Adrien Rabiot",
    teamId: "166",
    teamName: "Juventus",
    country: "France",
    goalsCount: 2,
    homeGoals: 2,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "118207",
    name: "Andre Silva",
    teamId: "13201",
    teamName: "RB Leipzig",
    country: "Portugal",
    goalsCount: 2,
    homeGoals: 2,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "134493",
    name: "Maryan Shved",
    teamId: "716",
    teamName: "FC Shakhtar Donetsk",
    country: "Ukraine",
    goalsCount: 2,
    homeGoals: 0,
    awayGoals: 2,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "86050",
    name: "Mislav Orsic",
    teamId: "653",
    teamName: "Dinamo Zagreb",
    country: "Croatia",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "100443",
    name: "Mohamed Salah Ghaly",
    teamId: "25",
    teamName: "Liverpool",
    country: "Egypt",
    goalsCount: 2,
    homeGoals: 2,
    awayGoals: 0,
    homePenalty: 1,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "146547",
    name: "Francisco Trincao",
    teamId: "466",
    teamName: "Sporting CP",
    country: "Portugal",
    goalsCount: 2,
    homeGoals: 0,
    awayGoals: 2,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "138918",
    name: "Richarlison de Andrade",
    teamId: "33",
    teamName: "Tottenham Hotspur",
    country: "Brazil",
    goalsCount: 2,
    homeGoals: 2,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "103915",
    name: "Raphael Guerreiro",
    teamId: "99",
    teamName: "Borussia Dortmund",
    country: "Portugal",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "170717",
    name: "Kamal Sowah",
    teamId: "148",
    teamName: "Club Brugge",
    country: "Ghana",
    goalsCount: 2,
    homeGoals: 1,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "135853",
    name: "Andre Zambo Anguissa",
    teamId: "1419",
    teamName: "Napoli",
    country: "Cameroon",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "172901",
    name: "Khvicha Kvaratskhelia",
    teamId: "1419",
    teamName: "Napoli",
    country: "Georgia",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "78745",
    name: "Steven Berghuis",
    teamId: "253",
    teamName: "AFC Ajax",
    country: "Netherlands",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "145064",
    name: "Marcus Edwards",
    teamId: "466",
    teamName: "Sporting CP",
    country: "England",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "80902",
    name: "Neymar da Silva Santos Junior",
    teamId: "271",
    teamName: "Paris Saint Germain (PSG)",
    country: "Brazil",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "145273",
    name: "Tanguy Ndombele Alvaro",
    teamId: "1419",
    teamName: "Napoli",
    country: "France",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 2,
  },
  {
    playerId: "161804",
    name: "Ferran Torres",
    teamId: "84",
    teamName: "FC Barcelona",
    country: "Spain",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 2,
  },
  {
    playerId: "105028",
    name: "Joao Paulo Dias Fernandes",
    teamId: "466",
    teamName: "Sporting CP",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 3,
  },
  {
    playerId: "145330",
    name: "Amine Harit",
    teamId: "211",
    teamName: "Marseille",
    country: "Morocco",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "154969",
    name: "Andreas Skov Olsen",
    teamId: "148",
    teamName: "Club Brugge",
    country: "Denmark",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "101117",
    name: "Riyad Mahrez",
    teamId: "26",
    teamName: "Manchester City",
    country: "Algeria",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 1,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "30565",
    name: "Marco Reus",
    teamId: "99",
    teamName: "Borussia Dortmund",
    country: "Germany",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "161244",
    name: "Rodrygo Silva De Goes",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Brazil",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "119097",
    name: "Julian Brandt",
    teamId: "99",
    teamName: "Borussia Dortmund",
    country: "Germany",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "64796",
    name: "Pierre-Emerick Aubameyang",
    teamId: "24",
    teamName: "Chelsea",
    country: "Gabon",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "27125",
    name: "Edin Dzeko",
    teamId: "152",
    teamName: "Inter Milan",
    country: "Bosnia-Herzegovina",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "84385",
    name: "Raheem Sterling",
    teamId: "24",
    teamName: "Chelsea",
    country: "England",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "99201",
    name: "Sadio Mane",
    teamId: "88",
    teamName: "Bayern Munchen",
    country: "Senegal",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "175093",
    name: "Mohamed Simakan",
    teamId: "13201",
    teamName: "RB Leipzig",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "29326",
    name: "Tjaronn Chery",
    teamId: "607",
    teamName: "Maccabi Haifa",
    country: "Suriname",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "116575",
    name: "Alex Grimaldo",
    teamId: "463",
    teamName: "Benfica",
    country: "Spain",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "123617",
    name: "Reece James",
    teamId: "24",
    teamName: "Chelsea",
    country: "England",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "153911",
    name: "Santiago Federico Valverde Dipetta",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Uruguay",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "153177",
    name: "Arthur Gomes",
    teamId: "466",
    teamName: "Sporting CP",
    country: "Brazil",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 1,
    subNum: 1,
  },
  {
    playerId: "212835",
    name: "Antonio Eromonsele Nordby Nusa",
    teamId: "148",
    teamName: "Club Brugge",
    country: "Norway",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 2,
  },
  {
    playerId: "27008",
    name: "Eric Maxim Choupo-Moting",
    teamId: "88",
    teamName: "Bayern Munchen",
    country: "Cameroon",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 1,
    subNum: 1,
  },
  {
    playerId: "119973",
    name: "Marco Asensio Willemsen",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Spain",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 3,
  },
  {
    playerId: "172275",
    name: "Lassina Traore",
    teamId: "716",
    teamName: "FC Shakhtar Donetsk",
    country: "Burkina Faso",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 3,
  },
  {
    playerId: "28879",
    name: "Eden Hazard",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Belgium",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 1,
    subNum: 1,
  },
  {
    playerId: "167577",
    name: "Karim Adeyemi",
    teamId: "99",
    teamName: "Borussia Dortmund",
    country: "Germany",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 1,
  },
  {
    playerId: "179232",
    name: "Tommaso Pobega",
    teamId: "150",
    teamName: "AC Milan",
    country: "Italy",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 3,
  },
  {
    playerId: "139185",
    name: "Dean David",
    teamId: "607",
    teamName: "Maccabi Haifa",
    country: "Israel",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "82034",
    name: "John Stones",
    teamId: "26",
    teamName: "Manchester City",
    country: "England",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 1,
    subNum: 0,
  },
  {
    playerId: "117539",
    name: "Franck Kessie",
    teamId: "84",
    teamName: "FC Barcelona",
    country: "Cote D Ivoire",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "150245",
    name: "Phil Foden",
    teamId: "26",
    teamName: "Manchester City",
    country: "England",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 1,
  },
  {
    playerId: "136177",
    name: "Mario Hermoso Canseco",
    teamId: "109",
    teamName: "Atletico Madrid",
    country: "Spain",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 1,
  },
  {
    playerId: "106101",
    name: "Serge Gnabry",
    teamId: "88",
    teamName: "Bayern Munchen",
    country: "Germany",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "175647",
    name: "Wesley Fofana",
    teamId: "24",
    teamName: "Chelsea",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "116026",
    name: "Matteo Politano",
    teamId: "1419",
    teamName: "Napoli",
    country: "Italy",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 1,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "116358",
    name: "Chancel Mbemba Mangulu",
    teamId: "211",
    teamName: "Marseille",
    country: "Democratic Rep Congo",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "96170",
    name: "Arkadiusz Milik",
    teamId: "166",
    teamName: "Juventus",
    country: "Poland",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "170580",
    name: "Julian Alvarez",
    teamId: "26",
    teamName: "Manchester City",
    country: "Argentina",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "78416",
    name: "Antoine Griezmann",
    teamId: "109",
    teamName: "Atletico Madrid",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 2,
  },
  {
    playerId: "142995",
    name: "Nuno Santos",
    teamId: "466",
    teamName: "Sporting CP",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "28696",
    name: "Alexis Alejandro Sanchez",
    teamId: "211",
    teamName: "Marseille",
    country: "Chile",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "124263",
    name: "Jan Sykora",
    teamId: "2534",
    teamName: "FC Viktoria Plzen",
    country: "Czech",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "25358",
    name: "Luka Modric",
    teamId: "82",
    teamName: "Real Madrid",
    country: "Croatia",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "146749",
    name: "Youssef En-Nesyri",
    teamId: "86",
    teamName: "Sevilla",
    country: "Morocco",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "117850",
    name: "Lucas Hernandez",
    teamId: "88",
    teamName: "Bayern Munchen",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "134285",
    name: "Denzel Dumfries",
    teamId: "152",
    teamName: "Inter Milan",
    country: "Netherlands",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "150612",
    name: "Wenderson Galeno",
    teamId: "468",
    teamName: "FC Porto",
    country: "Brazil",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "146446",
    name: "Ruben Dias",
    teamId: "26",
    teamName: "Manchester City",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 2,
    subNum: 0,
  },
  {
    playerId: "96450",
    name: "Hakan Calhanoglu",
    teamId: "152",
    teamName: "Inter Milan",
    country: "Turkey",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "178204",
    name: "Zaidu Sanusi",
    teamId: "468",
    teamName: "FC Porto",
    country: "Nigeria",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "66461",
    name: "Olivier Giroud",
    teamId: "150",
    teamName: "AC Milan",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 1,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "133867",
    name: "Oleksandr Zubkov",
    teamId: "716",
    teamName: "FC Shakhtar Donetsk",
    country: "Ukraine",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "168332",
    name: "Leonardo Balerdi",
    teamId: "211",
    teamName: "Marseille",
    country: "Argentina",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "60856",
    name: "Joel Matip",
    teamId: "25",
    teamName: "Liverpool",
    country: "Cameroon",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "153421",
    name: "Weston Mckennie",
    teamId: "166",
    teamName: "Juventus",
    country: "USA",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 1,
  },
  {
    playerId: "109253",
    name: "Robert Andrich",
    teamId: "165",
    teamName: "Bayer Leverkusen",
    country: "Germany",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "147622",
    name: "David Neres Campos",
    teamId: "463",
    teamName: "Benfica",
    country: "Brazil",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "168304",
    name: "Jesper Lindstrom",
    teamId: "423",
    teamName: "Eintracht Frankfurt",
    country: "Denmark",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "225688",
    name: "Abakar Sylla",
    teamId: "148",
    teamName: "Club Brugge",
    country: "",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "143279",
    name: "Dusan Vlahovic",
    teamId: "166",
    teamName: "Juventus",
    country: "Serbia",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "95598",
    name: "Joao Mario",
    teamId: "463",
    teamName: "Benfica",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 1,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "115258",
    name: "Rafael Ferreira Silva",
    teamId: "463",
    teamName: "Benfica",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "154647",
    name: "Joao Pedro Neves Filipe",
    teamId: "70",
    teamName: "Celtic FC",
    country: "Portugal",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "126824",
    name: "Steven Bergwijn",
    teamId: "253",
    teamName: "AFC Ajax",
    country: "Netherlands",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "96746",
    name: "Andres Mateus Uribe Villa",
    teamId: "468",
    teamName: "FC Porto",
    country: "Colombia",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 1,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "161537",
    name: "Giovanni Di Lorenzo",
    teamId: "1419",
    teamName: "Napoli",
    country: "Italy",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "151072",
    name: "Edson Omar Alvarez Velazquez",
    teamId: "253",
    teamName: "AFC Ajax",
    country: "Mexico",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "162774",
    name: "Moussa Diaby",
    teamId: "165",
    teamName: "Bayer Leverkusen",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "134153",
    name: "Christopher Nkunku",
    teamId: "13201",
    teamName: "RB Leipzig",
    country: "France",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "145108",
    name: "Trent Arnold",
    teamId: "25",
    teamName: "Liverpool",
    country: "England",
    goalsCount: 1,
    homeGoals: 1,
    awayGoals: 0,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
  {
    playerId: "159607",
    name: "Luis Fernando Diaz Marulanda",
    teamId: "25",
    teamName: "Liverpool",
    country: "Colombia",
    goalsCount: 1,
    homeGoals: 0,
    awayGoals: 1,
    homePenalty: 0,
    awayPenalty: 0,
    matchNum: 3,
    subNum: 0,
  },
];
